### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by imjamesb** [TooTallNate/ansi-canvas#9]
```
module.js:557
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/adm/Documents/Projects/ihack2712/theteamcoders.api.v2/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by CodeMan99** [comment]
You have provided zero information. The "canvas.node" file is native code that must be compiled on your machine before `require` is able to load it.

You have also filed a report on the incorrect repository. The "canvas.node" file is created by [node-canvas](https://github.com/Automattic/node-canvas). Open an issue there, providing the output of `npm install canvas` in your report.
